<a href="https://colab.research.google.com/github/THEFOOL-I/Dataset-Summary-Report-using-Python-and-Pandas/blob/main/pandas1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np
import pandas as pd

In [23]:
#loading data from a csv file
df=pd.read_csv("Day7_Student_Dataset.csv")
print(df)

    Student_ID           Name  Age            Course  Marks  \
0         1001   Aarav Sharma   19      Data Science   87.0
1         1002      Zoya Khan   20                AI   92.0
2         1003    Rohan Mehta   18  Computer Science   76.0
3         1004   Ananya Singh   21      Data Science   81.0
4         1005      Kabir Ali   19                AI   69.0
5         1006   Ishita Gupta   20  Computer Science   88.0
6         1007   Aditya Verma   22      Data Science   95.0
7         1008     Sara Ahmed   19                AI   73.0
8         1009     Arjun Nair   18  Computer Science   84.0
9         1010     Mehak Bhat   21      Data Science   79.0
10        1011  Vivaan Kapoor   20                AI   91.0
11        1012      Aisha Mir   19  Computer Science   68.0
12        1013      Rahul Das   23      Data Science   72.0
13        1014     Sana Malik   18                AI   89.0
14        1015    Karan Joshi   20  Computer Science   77.0
15        1016    Hiba Sheikh   21      Data Science   94.0
16        1017      Dev Patel   19                AI   86.0
17        1018      Manya Rao   22  Computer Science   70.0
18        1019      Yusuf Dar   20      Data Science    NaN
19        1020    Priya Menon   21                AI   90.0
20        1021     Aman Kumar   18  Computer Science   74.0
21        1022     Alina Shah   19      Data Science   96.0
22        1023    Nikhil Sood   22                AI   78.0
23        1024    Maryam Khan   20  Computer Science   85.0
24        1025   Reyansh Jain   21      Data Science   80.0

    Attendance_Percentage        City
0                    91.0    Srinagar
1                    95.0       Delhi
2                    82.0      Mumbai
3                    88.0    Srinagar
4                    76.0     Lucknow
5                    93.0   Bengaluru
6                    97.0        Pune
7                     NaN   Hyderabad
8                    86.0       Kochi
9                    90.0    Srinagar
10                   94.0      Jaipur
11                   72.0       Delhi
12                   81.0     Kolkata
13                   92.0         NaN
14                   85.0  Chandigarh
15                   96.0    Srinagar
16                   89.0   Ahmedabad
17                   74.0   Bengaluru
18                   87.0    Srinagar
19                   91.0     Chennai
20                   78.0       Delhi
21                   98.0    Srinagar
22                   83.0        Pune
23                   88.0   Hyderabad
24                   84.0     Kolkata

In [25]:
#showing first few rows
df.head(10)

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
4,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow
5,1006,Ishita Gupta,20,Computer Science,88.0,93.0,Bengaluru
6,1007,Aditya Verma,22,Data Science,95.0,97.0,Pune
7,1008,Sara Ahmed,19,AI,73.0,NaN,Hyderabad
8,1009,Arjun Nair,18,Computer Science,84.0,86.0,Kochi
9,1010,Mehak Bhat,21,Data Science,79.0,90.0,Srinagar

In [26]:
#showing last few rows
df.tail(10)

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
15,1016,Hiba Sheikh,21,Data Science,94.0,96.0,Srinagar
16,1017,Dev Patel,19,AI,86.0,89.0,Ahmedabad
17,1018,Manya Rao,22,Computer Science,70.0,74.0,Bengaluru
18,1019,Yusuf Dar,20,Data Science,NaN,87.0,Srinagar
19,1020,Priya Menon,21,AI,90.0,91.0,Chennai
20,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
21,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
23,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

In [27]:
#displaying some randow rows
df.sample(6)

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
20,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
17,1018,Manya Rao,22,Computer Science,70.0,74.0,Bengaluru
21,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
15,1016,Hiba Sheikh,21,Data Science,94.0,96.0,Srinagar
9,1010,Mehak Bhat,21,Data Science,79.0,90.0,Srinagar
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar

In [28]:
#displaying shape of dataset
df.shape

(25, 7)

In [29]:
#data inspection
#1) understanding the overall structure
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             25 non-null     int64
 1   Name                   25 non-null     object
 2   Age                    25 non-null     int64
 3   Course                 25 non-null     object
 4   Marks                  24 non-null     float64
 5   Attendance_Percentage  24 non-null     float64
 6   City                   24 non-null     object
dtypes: float64(2), int64(2), object(3)
memory usage: 1.5+ KB

In [30]:
#2 getting datatypes of data stored under columns or each Series
df.dtypes

Student_ID                 int64
Name                      object
Age                        int64
Course                    object
Marks                    float64
Attendance_Percentage    float64
City                      object
dtype: object

In [13]:
#3 printing each column name
df.columns

Index(['Student_ID', 'Name', 'Age', 'Course', 'Marks', 'Attendance_Percentage',
       'City'],
      dtype='object')

In [31]:
#4 getting index of rows or total number of rows
df.index

RangeIndex(start=0, stop=25, step=1)

In [32]:
#5 basic statistical features of dataset
df.describe()

        Student_ID        Age      Marks  Attendance_Percentage
count    25.000000  25.000000  24.000000              24.000000
mean   1013.000000  20.000000  82.250000              87.083333
std       7.359801   1.414214   8.689074               7.252686
min    1001.000000  18.000000  68.000000              72.000000
25%    1007.000000  19.000000  75.500000              82.750000
50%    1013.000000  20.000000  82.500000              88.000000
75%    1019.000000  21.000000  89.250000              92.250000
max    1025.000000  23.000000  96.000000              98.000000

In [33]:
#6 identifying noticiable missing values
df.isnull()

    Student_ID   Name    Age  Course  Marks  Attendance_Percentage   City
0        False  False  False   False  False                  False  False
1        False  False  False   False  False                  False  False
2        False  False  False   False  False                  False  False
3        False  False  False   False  False                  False  False
4        False  False  False   False  False                  False  False
5        False  False  False   False  False                  False  False
6        False  False  False   False  False                  False  False
7        False  False  False   False  False                   True  False
8        False  False  False   False  False                  False  False
9        False  False  False   False  False                  False  False
10       False  False  False   False  False                  False  False
11       False  False  False   False  False                  False  False
12       False  False  False   False  False                  False  False
13       False  False  False   False  False                  False   True
14       False  False  False   False  False                  False  False
15       False  False  False   False  False                  False  False
16       False  False  False   False  False                  False  False
17       False  False  False   False  False                  False  False
18       False  False  False   False   True                  False  False
19       False  False  False   False  False                  False  False
20       False  False  False   False  False                  False  False
21       False  False  False   False  False                  False  False
22       False  False  False   False  False                  False  False
23       False  False  False   False  False                  False  False
24       False  False  False   False  False                  False  False

In [34]:
#quantifying null values
df.isnull().sum()

Student_ID               0
Name                     0
Age                      0
Course                   0
Marks                    1
Attendance_Percentage    1
City                     1
dtype: int64

In [ ]:
# Final Observations
#The dataset contains 25 rows and 7 columns. The available features are Student_ID, Name, Age, Course, Marks, Attendance_Percentage, and City.
#The dataset contains 2 integer columns (Student_ID and Age), 2 floating-point columns (Marks and Attendance_Percentage), and 3 object/string columns (Name, Course, and City).
#The dataset has missing values in three columns. The Marks column has 1 missing value, the Attendance_Percentage column has 1 missing value, and the City column has 1 missing value. The remaining columns do not contain missing values.
#The index contains 25 entries ranging from 0 to 24. The dataset mainly contains student-related information such as their course, marks, attendance percentage, age, and city. From the basic statistical analysis, the numerical features can be further examined to understand the students' performance and attendance.